[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "example-pkg-naturalett>=14.9",
    "pandas==2.2.3",
]
